name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            build/main
            build/tests
            build/benchmark_add
  
  tests:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x tests && ./tests

  benchmark:
    needs: [build, run]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x benchmark_add && ./benchmark_add
  
  run:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
      - run: chmod +x main && ./main 2 7
